import { useMemo, useState } from "react";
import {
  Activity,
  AlertTriangle,
  BarChart3,
  CheckCircle2,
  Clock3,
  Download,
  Droplets,
  FileText,
  Fuel,
  Gauge,
  Printer,
  Server,
  ShieldCheck,
  Snowflake,
  Thermometer,
  Truck,
  Wind,
  Zap,
} from "lucide-react";

import { useStation } from "../context/StationContext";
import "./Reports.css";

type ReportPeriod = "24h" | "7d" | "30d";
type ReportType = "operational" | "energy" | "environment" | "logistics";

interface Metric {
  label: string;
  value: string;
  detail: string;
  status: "nominal" | "watch" | "warning";
  icon: React.ReactNode;
}

interface EventItem {
  time: string;
  system: string;
  event: string;
  status: "Closed" | "Acknowledged" | "Monitoring";
}

export default function Reports() {
  const { stationId, setStationId } = useStation();

  const [period, setPeriod] = useState<ReportPeriod>("24h");
  const [reportType, setReportType] =
    useState<ReportType>("operational");

  const stationName =
    stationId === "bharati" ? "Bharati" : "Maitri";

  const generatedAt = "27 Sep 2026 · 00:35 IST";

  const metrics: Metric[] = useMemo(
    () => [
      {
        label: "Station Availability",
        value: "99.4%",
        detail: "Operational uptime",
        status: "nominal",
        icon: <Activity size={20} />,
      },
      {
        label: "Electrical Demand",
        value: stationId === "bharati" ? "356 kW" : "318 kW",
        detail: "Current simulated demand",
        status: "nominal",
        icon: <Zap size={20} />,
      },
      {
        label: "Fuel Endurance",
        value: stationId === "bharati" ? "84 days" : "91 days",
        detail: "Estimated reserve endurance",
        status: "watch",
        icon: <Fuel size={20} />,
      },
      {
        label: "Active Alerts",
        value: "01",
        detail: "Requires operator review",
        status: "warning",
        icon: <AlertTriangle size={20} />,
      },
    ],
    [stationId]
  );

  const events: EventItem[] = [
    {
      time: "00:18",
      system: "Power Generation",
      event: "Generator load exceeded nominal monitoring band",
      status: "Monitoring",
    },
    {
      time: "23:46",
      system: "Environment",
      event: "External visibility crossed configured threshold",
      status: "Acknowledged",
    },
    {
      time: "22:51",
      system: "Communications",
      event: "Satellite latency excursion returned to normal range",
      status: "Closed",
    },
    {
      time: "21:35",
      system: "Fuel System",
      event: "Fuel endurance entered configured monitoring window",
      status: "Acknowledged",
    },
  ];

  const reportLabel = {
    operational: "Integrated Operational Report",
    energy: "Energy Systems Report",
    environment: "Environmental Conditions Report",
    logistics: "Logistics & Resupply Report",
  }[reportType];

  function handlePrint() {
    window.print();
  }

  function handleExport() {
    const report = [
      "POLARIS ANTARCTIC DIGITAL TWIN",
      "PROTOTYPE OPERATIONAL REPORT",
      "",
      `Station: ${stationName}`,
      `Report: ${reportLabel}`,
      `Period: ${period}`,
      `Generated: ${generatedAt}`,
      "",
      "NOTICE:",
      "This report contains simulated prototype telemetry and is not an official NCPOR operational record.",
      "",
      "SUMMARY",
      `Station Availability: ${metrics[0].value}`,
      `Electrical Demand: ${metrics[1].value}`,
      `Fuel Endurance: ${metrics[2].value}`,
      `Active Alerts: ${metrics[3].value}`,
      "",
      "ENVIRONMENT",
      "External Temperature: -21.4 C",
      "Wind Speed: 46 km/h",
      "Pressure: 974 hPa",
      "Visibility: 5.7 km",
      "",
      "LOGISTICS",
      "Food Reserve: 137 days",
      "Medical Stock: 94%",
      "Critical Spares: 84%",
      "",
      "Generated by POLARIS prototype decision-support interface.",
    ].join("\n");

    const blob = new Blob([report], {
      type: "text/plain;charset=utf-8",
    });

    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");

    link.href = url;
    link.download = `POLARIS_${stationName}_${reportType}_${period}.txt`;
    document.body.appendChild(link);
    link.click();

    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  return (
    <main className="reports-page">
      {/* HEADER */}
      <section className="reports-header">
        <div>
          <p className="reports-eyebrow">
            POLARIS / OPERATIONS / REPORTING
          </p>

          <h1>Operational Reports</h1>

          <p className="reports-description">
            Consolidated station reporting for infrastructure,
            energy, environment, logistics and operational events
            across India's Antarctic research stations.
          </p>
        </div>

        <div className="reports-station-block">
          <span className="reports-small-label">
            ACTIVE STATION
          </span>

          <div className="reports-station-toggle">
            <button
              className={
                stationId === "maitri" ? "station-active" : ""
              }
              onClick={() => setStationId("maitri")}
            >
              MAITRI
            </button>

            <button
              className={
                stationId === "bharati" ? "station-active" : ""
              }
              onClick={() => setStationId("bharati")}
            >
              BHARATI
            </button>
          </div>
        </div>
      </section>

      {/* STATUS STRIP */}
      <section className="reports-status-strip">
        <div className="status-left">
          <span className="status-dot" />
          <strong>REPORTING SYSTEM ONLINE</strong>

          <span className="status-divider" />

          <span>SIMULATED DATASET</span>
        </div>

        <div className="status-right">
          <span>
            STATION <strong>{stationName.toUpperCase()}</strong>
          </span>

          <span>
            REPORT ID{" "}
            <strong>
              POL-{stationId === "bharati" ? "BHR" : "MTR"}-0927
            </strong>
          </span>
        </div>
      </section>

      {/* PROTOTYPE NOTICE */}
      <section className="reports-policy">
        <ShieldCheck size={18} />

        <strong>PROTOTYPE REPORTING</strong>

        <span>
          Values presented in this report are simulated for Digital
          Twin demonstration and are not live NCPOR operational
          records.
        </span>
      </section>

      {/* CONTROL BAR */}
      <section className="report-control-panel">
        <div className="control-group">
          <span className="control-label">REPORT TYPE</span>

          <select
            value={reportType}
            onChange={(e) =>
              setReportType(e.target.value as ReportType)
            }
          >
            <option value="operational">
              Integrated Operational
            </option>
            <option value="energy">Energy Systems</option>
            <option value="environment">
              Environmental Conditions
            </option>
            <option value="logistics">
              Logistics & Resupply
            </option>
          </select>
        </div>

        <div className="control-group">
          <span className="control-label">REPORTING WINDOW</span>

          <div className="period-selector">
            <button
              className={period === "24h" ? "period-active" : ""}
              onClick={() => setPeriod("24h")}
            >
              24 HOURS
            </button>

            <button
              className={period === "7d" ? "period-active" : ""}
              onClick={() => setPeriod("7d")}
            >
              7 DAYS
            </button>

            <button
              className={period === "30d" ? "period-active" : ""}
              onClick={() => setPeriod("30d")}
            >
              30 DAYS
            </button>
          </div>
        </div>

        <div className="report-actions">
          <button className="secondary-action" onClick={handlePrint}>
            <Printer size={16} />
            PRINT
          </button>

          <button className="primary-action" onClick={handleExport}>
            <Download size={16} />
            EXPORT REPORT
          </button>
        </div>
      </section>

      {/* REPORT TITLE */}
      <section className="report-document-header">
        <div>
          <p className="reports-eyebrow">CURRENT REPORT</p>

          <h2>{reportLabel}</h2>

          <p>
            {stationName} Antarctic Research Station ·{" "}
            {period === "24h"
              ? "Previous 24 hours"
              : period === "7d"
              ? "Previous 7 days"
              : "Previous 30 days"}
          </p>
        </div>

        <div className="report-generated">
          <Clock3 size={16} />

          <div>
            <span>GENERATED</span>
            <strong>{generatedAt}</strong>
          </div>
        </div>
      </section>

      {/* SUMMARY METRICS */}
      <section className="report-metrics">
        {metrics.map((metric) => (
          <article className="report-metric-card" key={metric.label}>
            <div className="metric-top">
              <div className="metric-icon">{metric.icon}</div>

              <span className={`metric-status ${metric.status}`}>
                {metric.status.toUpperCase()}
              </span>
            </div>

            <p>{metric.label}</p>
            <h3>{metric.value}</h3>
            <span className="metric-detail">{metric.detail}</span>
          </article>
        ))}
      </section>

      {/* SYSTEM OVERVIEW */}
      <section className="report-section">
        <div className="section-heading">
          <div>
            <p className="reports-eyebrow">
              SYSTEM PERFORMANCE
            </p>
            <h2>Station Operational Summary</h2>
          </div>

          <BarChart3 size={24} />
        </div>

        <div className="system-summary-grid">
          {/* ENERGY */}
          <article className="summary-panel">
            <div className="summary-panel-title">
              <Zap size={19} />
              <div>
                <span>ENE-01</span>
                <h3>Energy System</h3>
              </div>
            </div>

            <div className="summary-data-row">
              <span>Generation</span>
              <strong>418 kW</strong>
            </div>

            <div className="summary-data-row">
              <span>Demand</span>
              <strong>356 kW</strong>
            </div>

            <div className="summary-data-row">
              <span>Reserve Capacity</span>
              <strong>+62 kW</strong>
            </div>

            <div className="summary-progress">
              <div className="progress-info">
                <span>System utilisation</span>
                <strong>85%</strong>
              </div>

              <div className="progress-track">
                <div style={{ width: "85%" }} />
              </div>
            </div>
          </article>

          {/* ENVIRONMENT */}
          <article className="summary-panel">
            <div className="summary-panel-title">
              <Snowflake size={19} />
              <div>
                <span>ENV-01</span>
                <h3>Environment</h3>
              </div>
            </div>

            <div className="summary-data-row">
              <span>
                <Thermometer size={14} /> Temperature
              </span>
              <strong>-21.4°C</strong>
            </div>

            <div className="summary-data-row">
              <span>
                <Wind size={14} /> Wind
              </span>
              <strong>46 km/h</strong>
            </div>

            <div className="summary-data-row">
              <span>
                <Gauge size={14} /> Pressure
              </span>
              <strong>974 hPa</strong>
            </div>

            <div className="summary-data-row">
              <span>
                <Droplets size={14} /> Visibility
              </span>
              <strong>5.7 km</strong>
            </div>
          </article>

          {/* LOGISTICS */}
          <article className="summary-panel">
            <div className="summary-panel-title">
              <Truck size={19} />
              <div>
                <span>LOG-01</span>
                <h3>Logistics & Resupply</h3>
              </div>
            </div>

            <div className="summary-data-row">
              <span>Food Reserve</span>
              <strong>137 days</strong>
            </div>

            <div className="summary-data-row">
              <span>Fuel Reserve</span>
              <strong>84 days</strong>
            </div>

            <div className="summary-data-row">
              <span>Medical Stock</span>
              <strong>94%</strong>
            </div>

            <div className="summary-data-row">
              <span>Critical Spares</span>
              <strong>84%</strong>
            </div>
          </article>

          {/* INFRASTRUCTURE */}
          <article className="summary-panel">
            <div className="summary-panel-title">
              <Server size={19} />
              <div>
                <span>INF-01</span>
                <h3>Infrastructure</h3>
              </div>
            </div>

            <div className="summary-data-row">
              <span>Power Generation</span>
              <strong className="state-nominal">ONLINE</strong>
            </div>

            <div className="summary-data-row">
              <span>HVAC</span>
              <strong className="state-nominal">NOMINAL</strong>
            </div>

            <div className="summary-data-row">
              <span>Water System</span>
              <strong className="state-nominal">NOMINAL</strong>
            </div>

            <div className="summary-data-row">
              <span>Satellite Link</span>
              <strong className="state-watch">MONITOR</strong>
            </div>
          </article>
        </div>
      </section>

      {/* TREND SECTION */}
      <section className="report-section">
        <div className="section-heading">
          <div>
            <p className="reports-eyebrow">
              PERFORMANCE TREND
            </p>
            <h2>Operational Load Profile</h2>
          </div>

          <Activity size={24} />
        </div>

        <div className="trend-panel">
          <div className="trend-y-axis">
            <span>450</span>
            <span>400</span>
            <span>350</span>
            <span>300</span>
            <span>250</span>
          </div>

          <div className="trend-chart">
            <div className="grid-line line-1" />
            <div className="grid-line line-2" />
            <div className="grid-line line-3" />
            <div className="grid-line line-4" />

            <svg
              viewBox="0 0 1000 230"
              preserveAspectRatio="none"
              className="trend-svg"
            >
              <polyline
                className="demand-line"
                points="
                  0,165
                  90,155
                  180,160
                  270,137
                  360,128
                  450,103
                  540,92
                  630,110
                  720,82
                  810,100
                  900,93
                  1000,106
                "
              />

              <polyline
                className="capacity-line"
                points="
                  0,58
                  90,58
                  180,58
                  270,58
                  360,58
                  450,58
                  540,58
                  630,58
                  720,58
                  810,58
                  900,58
                  1000,58
                "
              />
            </svg>

            <div className="trend-times">
              <span>00:00</span>
              <span>04:00</span>
              <span>08:00</span>
              <span>12:00</span>
              <span>16:00</span>
              <span>20:00</span>
              <span>24:00</span>
            </div>
          </div>
        </div>

        <div className="chart-legend">
          <span>
            <i className="legend-demand" />
            Electrical demand
          </span>

          <span>
            <i className="legend-capacity" />
            Available generation capacity
          </span>
        </div>
      </section>

      {/* EVENTS */}
      <section className="report-section">
        <div className="section-heading">
          <div>
            <p className="reports-eyebrow">
              OPERATIONS LOG
            </p>
            <h2>Recent Operational Events</h2>
          </div>

          <FileText size={23} />
        </div>

        <div className="events-table-wrapper">
          <table className="events-table">
            <thead>
              <tr>
                <th>TIME</th>
                <th>SUBSYSTEM</th>
                <th>EVENT</th>
                <th>STATUS</th>
              </tr>
            </thead>

            <tbody>
              {events.map((event, index) => (
                <tr key={`${event.time}-${index}`}>
                  <td className="event-time">{event.time} IST</td>
                  <td>{event.system}</td>
                  <td>{event.event}</td>
                  <td>
                    <span
                      className={`event-status ${event.status
                        .toLowerCase()
                        .replace(" ", "-")}`}
                    >
                      {event.status === "Closed" && (
                        <CheckCircle2 size={13} />
                      )}

                      {event.status}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      {/* ASSESSMENT */}
      <section className="report-assessment">
        <div className="assessment-icon">
          <ShieldCheck size={25} />
        </div>

        <div className="assessment-content">
          <p className="reports-eyebrow">
            AUTOMATED ASSESSMENT
          </p>

          <h3>Station resilience remains within nominal limits.</h3>

          <p>
            Simulated telemetry indicates adequate electrical
            reserve capacity and logistics endurance. Environmental
            conditions require continued visibility monitoring, while
            the fuel system remains inside the configured watch
            window.
          </p>
        </div>

        <div className="assessment-state">
          <span>OVERALL STATE</span>
          <strong>NOMINAL</strong>
        </div>
      </section>

      {/* FOOTER */}
      <footer className="report-footer">
        <div>
          <strong>POLARIS</strong>
          <span>Antarctic Digital Twin · SIH26060</span>
        </div>

        <div>
          <span>
            Prototype decision-support interface · Simulated data
          </span>
        </div>
      </footer>
    </main>
  );
}